const Tasks = [
  {
    id: 1,
    round: 1,
    designer: "Rohullah",
    time: 24,
    group: "UMS && Boxmarket",
    info: `Create projects,Develope Platform`,
    link: "",
    finalLink: "https://dev_group_mu.vercel.app",
    state: "in progress",
  },
  {
    id: 1,
    round: 1,
    designer: "Rohullah",
    time: 24,
    group: "UMS && Boxmarket",
    info: `Create projects, improve the platform`,
    link: "",
    finalLink: "https://dev_group_mu.vercel.app",
    state: "in progress",
  },
  {
    id: 2,
    round: 1,
    designer: "latif",
    time: 24,
    group: "Boxmarket",
    info: `create a source file which contains all the product info`,
    link: "",
    finalLink: "",
    state: "in progress",
  },
  {
    id: 3,
    round: 1,
    designer: "mahram",
    time: 24,
    group: "Boxmarket",
    info: `یک لاگین فارمی که در اول سایت باشد وقتی مشتری وارد میشود پرسیده شوه که ایا میخواهید حساب جدید تشکیل دهید یا به حیث مهمان ادامه دهید`,
    link: "",
    finalLink: "",
    state: "in progress",
  },
];
export default Tasks;
