const Tasks = [
  {
    id: 3001,
    round: 1,
    designer: "Rohullah",
    time: 24 + "hours",
    title: "DevGroup React Project Development",
    info: `Create prjects, import components. modern UIs`,
    sample: "",
    finalLink: "https://dev_group_mu.vercel.app",
    state: "in progress",
  },
  {
    id: 3002,
    round: 1,
    designer: "Rohullah",
    time: 24 + "hours",
    title: "DevGroup React Project Development",
    info: `Create prjects, import components. modern UIs`,
    sample: "",
    finalLink: "https://dev_group_mu.vercel.app",
    state: "in progress",
  },
  {
    id: 3003,
    round: 1,
    designer: "Rohullah",
    time: 24 + "hours",
    title: "DevGroup React Project Development",
    info: `Create prjects, import components. modern UIs`,
    sample: "",
    finalLink: "https://dev_group_mu.vercel.app",
    state: "in progress",
  },
  {
    id: 3004,
    round: 1,
    designer: "Rohullah",
    time: 24 + "hours",
    title: "DevGroup React Project Development",
    info: `Create prjects, import components. modern UIs`,
    sample: "",
    finalLink: "https://dev_group_mu.vercel.app",
    state: "in progress",
  },
];
export default Tasks;
